# Generated by Django 5.0.2 on 2024-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
