# Generated by Django 5.0.2 on 2024-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_student_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, null=True)),
                ('headof', models.CharField(max_length=100, null=True)),
                ('HOD', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
