# Generated by Django 5.0.2 on 2024-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_faculty_remove_student_id_alter_student_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
            ],
        ),
    ]
