# Generated by Django 5.0.2 on 2024-02-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_event_highlights_event_highlight_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
