# Generated by Django 5.0.2 on 2024-02-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('days', models.CharField(max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('club', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intake', models.IntegerField()),
                ('highlights', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.faculty')),
            ],
        ),
    ]
