# Generated by Django 5.0.2 on 2024-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='highlights',
        ),
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='highlight_event',
            field=models.TextField(default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
